### PR TITLE
Updated to Ensime 2.0.0. Using TypeAtPointReq for hover request

### PR DESCRIPTION
**Pull request by fede0664**
Updated to Ensime 2.0.0. 
Using TypeAtPointReq and TypeInfo.name + TypeInfo.fullName from the response for hover signature seems to be much more descriptive

### CODE REVIEW

**Comment by dragos** [comment]
I'm split on this, the reason why the code was commented was that the results are usually suboptimal. For example, for `List(1, 3).map(_.toString)`, hovering over `map`:

Now:

```
map[B,That](f:A=>B)(implicitbf:scala.collection.generic.CanBuildFrom[List[A],B,That]):That
```
With these changes:

```
((scala.Int) => scala.collection.TraversableLike.B) => (scala.collection.generic.CanBuildFrom[scala.collection.immutable.List[scala.Int], scala.collection.TraversableLike.B, scala.collection.TraversableLike.That]) => scala.collection.TraversableLike.That
```

I don't know why Ensime expands type-aliases in this request, but the result is quite unreadable. The previous version wasn't ideal either, but I'm putting this here for discussion.

**Comment by fede0664** [comment]
How about this, using TypeAtPointReq if DocUriAtPointReq returns an empty string?
At least this will fix not having hover detail for implicit local val types.

**Comment by dragos** [comment]
Good point! Let's do that!

**Comment by dragos** [comment]
One more thing, could you please update the changelog? I am starting to lose track of it and it ends up delaying the release.

**Pull request merged**
