### PR TITLE
Different extension icon.

### PR DESCRIPTION
**Pull request by tjm00**
How about something like this? #20

### CODE REVIEW

**Comment by dragos** [comment]
I like it! Thanks!

**Comment by kggp1995** [comment]
Not really sure if MSFT terms allow you to merge the Visual Studio Logo. Any confirmation on this available?

**Comment by dragos** [comment]
Valid concern. Can you provide more details why you think that's a problem? The license is the [MIT license](https://github.com/Microsoft/vscode/blob/master/LICENSE.txt) which allows derivative works.

**Comment by kggp1995** [comment]
The source code is MIT Licensed, agreed.

But, Mentioned - **"No logo, graphic, sound or image from _any_ Microsoft website may be copied or retransmitted unless expressly permitted by Microsoft."** from https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx

Hope this helps. Just ensuring there are no infringement issues from contributors you need to deal with.
Keep up the great work with the extension!!!
Keep them coming!

**Comment by dragos** [comment]
Thanks for the details.

IANAL but I don't think that applies. It's inside a section titled "Notice Specific to Documents Available on this Website" and it talks about Microsoft websites, while the code is hosted by GitHub. However, it would be good if @tjm00 could let us know if the logo was obtained via GitHub or some other means. Can you please confirm?

**Comment by tjm00** [comment]
Given that one of the [most popular extensions](https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons) in the marketplace, with over 1.8 million downloads and featured on the [front page](https://marketplace.visualstudio.com/vscode), uses the vscode icon as well, I can't imagine it being an issue. Oodles of extensions with many more downloads, even ones that have been featured, use the icon. However, I am uncertain exactly where the source image was taken from or if it even was taken from anywhere, as I merely tasked a graphic design acquaintance (that was looking for a way to start contributing) with this.

That said, if someone has a better idea for the design, I suspect my acquaintance would be willing to make that as well.

**Comment by kggp1995** [comment]
Hi @tjm00 , thank you for your observation, i'd like to recommend something like this:

sls-plugin-bg

This is just a broad stroke, hope you'll be able to pick up the idea :)

**Pull request merged**
