### PR TITLE
bump the server

### PR DESCRIPTION
**Pull request by fommil**

### CODE REVIEW

**Comment by dragos** [comment]
```

**Comment by dragos** [comment]
Looks like something changed in the way config is handled?

```
[error] /home/travis/build/dragos/dragos-vscode-scala/ensime-lsp/src/main/scala/org/github/dragos/vscode/ensime/EnsimeProjectServer.scala:26: could not find implicit value for parameter serverConfig: org.ensime.api.EnsimeServerConfig
[error]   val project = context.actorOf(Project(broadcaster), "project")
```

**Comment by fommil** [comment]
hmm, yeah you will need to construct the `Project` actor via `Project.props` now and that requires an `EnsimeServerConfig` instance. You can either use our support for reading one or just provide a hand crafted one with manual defaults for now. This is new support for allowing users to customise ensime internals (think scala-refactoring preferences and, later, banlists in exclusions / indexing)

**Comment by fommil** [comment]
`org.ensime.config.richconfig.parseServerConfig` for raw parsing or `Server.loadConfig` for the proper file location handling. Sorry, should maybe have put that somewhere more accessible.

**Comment by fommil** [comment]
oh, and when creating the actor system you may as well make the `Config` objects align by doing

```
ActorSystem.create("ENSIME", config)
```

**Comment by fommil** [comment]
https://github.com/ensime/ensime-server/issues/1815 would remove the need for that disgusting mutation around `Canon`

**Comment by dragos** [comment]
Give me a few days to catch up with things and I'll merge this. :)

**Comment by dragos** [comment]
Superseeded by #54

**Pull request closed without merging**
